# Generated by Django 5.2.13 on 2026-05-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('resumen', models.TextField()),
                ('contenido', models.TextField()),
                ('es_principal', models.BooleanField(default=False)),
            ],
        ),
    ]
