# Generated by Django 5.2.13 on 2026-05-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='es_principal',
        ),
        migrations.AddField(
            model_name='noticia',
            name='tipo',
            field=models.CharField(choices=[('principal', 'Principal'), ('secundaria', 'Secundaria'), ('mixta', 'Mixta')], default='secundaria', max_length=20),
        ),
    ]
