# Generated by Django 5.2.13 on 2026-05-19 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_remove_noticia_es_principal_noticia_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='tipo',
        ),
    ]
