# Generated by Django 5.2.13 on 2026-05-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_remove_noticia_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='resumen',
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/'),
        ),
    ]
