# Generated by Django 5.2.13 on 2026-05-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_remove_noticia_resumen_noticia_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='tendencia',
            field=models.BooleanField(default=False),
        ),
    ]
