# Generated by Django 5.2.11 on 2026-05-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0006_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBelico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia1', models.CharField(max_length=100)),
                ('familia2', models.CharField(max_length=100)),
                ('ganador', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
