# Generated by Django 5.2.11 on 2026-05-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0007_registrobelico'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(max_length=100)),
                ('pettadas', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-pettadas'],
            },
        ),
    ]
