# Generated by Django 5.2.11 on 2026-06-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0009_familia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrobelico',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
